### ISSUE TITLE
SonoranBot

### ISSUE THREAD

**Issue by Gameover562** [Sonoran-Software/SonoranCMS-Documentation#5]
Good morning,

I have this issue where everytime i tried to send a command to Sonoran bot in our discord i got this error message :

''An exception occurred in bot code. Notify my developer.''

![image](https://user-images.githubusercontent.com/70591603/223478676-fe884ac7-26fe-401e-8e63-884f5ed0094d.png)

Thank you !

**Comment by itismejoey** [comment]
Bring your issue to https://support.sonoransoftware.com/, this isn't the place to get support.
